"""Code-owned registries for routing, formulas, and planner validation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, FrozenSet, Tuple


TASK_TYPES: FrozenSet[str] = frozenset(
    {
        "capacitor_energy",
        "capacitance",
        "capacitor_charge",
        "ohm_law",
        "electric_power",
        "coulomb_force",
        "electric_field_point",
        "electric_field_force",
        "force_in_electric_field",
        "uniform_field_voltage",
        "electric_potential_point",
        "electrostatic_energy",
        "lc_frequency",
        "lc_period",
        "lc_energy",
        "inductive_reactance",
        "capacitive_reactance",
        "rlc_impedance",
        "power_factor",
        "inductance",
        "inductor_energy",
        "solenoid_magnetic_field",
        "solenoid_inductance",
        "turn_density",
        "magnetic_flux",
        "resultant_force",
        "equal_charge_coulomb",
        "multi_output",
        "dielectric_constant",
        "capacitor_final_voltage",
        "internal_resistance",
        "joule_heating",
        "electric_work",
        "uniform_field",
        "charged_particle_motion",
        "drift_current",
        "rc_circuit",
        "transformer",
        "lorentz_force",
        "wire_magnetic_force",
        "faraday_induction",
        "wheatstone_bridge",
        "meter_idealization",
        "measurement_error",
        "conceptual",
        "unknown",
    }
)

ANSWER_TYPES: FrozenSet[str] = frozenset({"numeric", "symbolic", "conceptual", "yes_no", "multi_output", "unknown"})
PLANNER_STATUSES: FrozenSet[str] = frozenset({"ok", "needs_fallback", "unsupported"})
SOLVE_STRATEGIES: FrozenSet[str] = frozenset({"direct", "sequential", "simultaneous", "conceptual"})
GEOMETRY_TEMPLATE_IDS: FrozenSet[str] = frozenset(
    {
        "two_charges_collinear",
        "point_on_midpoint",
        "point_on_perpendicular_bisector",
        "equilateral_triangle_vertex",
        "right_isosceles_triangle_vertex",
        "triangle_vertex",
        "triangle_sides",
        "square_vertex_field",
        "rectangle_vertex_field",
        "external_point_on_line",
    }
)

PRINCIPLE_IDS: FrozenSet[str] = frozenset(
    {
        "capacitor_core",
        "dc_circuit_core",
        "coulomb_core",
        "lc_core",
        "magnetic_core",
        "field_core",
        "vector_core",
        "rlc_core",
        "conceptual_core",
        "kirchhoff_core",
        "internal_resistance_core",
        "joule_heating_core",
        "charged_particle_core",
        "rc_core",
        "transformer_core",
        "induction_core",
        "topology_core",
        "symmetry_core",
        "measurement_core",
    }
)


@dataclass(frozen=True)
class FormulaSpec:
    formula_id: str
    task_type: str
    principle_id: str
    required_dimensions: Tuple[str, ...]
    target_dimension: str
    target_unit: str
    expression: str
    premise: str


FORMULA_REGISTRY: Dict[str, FormulaSpec] = {
    "capacitor_energy_voltage": FormulaSpec(
        "capacitor_energy_voltage",
        "capacitor_energy",
        "capacitor_core",
        ("capacitance", "voltage"),
        "energy",
        "J",
        "W = 0.5*C*U^2",
        "Capacitor energy relation W = 1/2 C U^2.",
    ),
    "capacitor_energy_charge": FormulaSpec(
        "capacitor_energy_charge",
        "capacitor_energy",
        "capacitor_core",
        ("charge", "capacitance"),
        "energy",
        "J",
        "W = Q^2/(2*C)",
        "Capacitor energy relation W = Q^2/(2C).",
    ),
    "capacitance": FormulaSpec(
        "capacitance",
        "capacitance",
        "capacitor_core",
        ("charge", "voltage"),
        "capacitance",
        "F",
        "C = Q/U",
        "Capacitance relation C = Q/U.",
    ),
    "capacitor_charge": FormulaSpec(
        "capacitor_charge",
        "capacitor_charge",
        "capacitor_core",
        ("capacitance", "voltage"),
        "charge",
        "C",
        "Q = C*U",
        "Capacitor charge relation Q = C U.",
    ),
    "capacitor_charge_energy_voltage": FormulaSpec(
        "capacitor_charge_energy_voltage",
        "capacitor_charge",
        "capacitor_core",
        ("energy", "voltage"),
        "charge",
        "C",
        "Q = 2*W/U",
        "Capacitor energy can be written W = 1/2 Q U, so Q = 2W/U.",
    ),
    "parallel_plate_charge": FormulaSpec(
        "parallel_plate_charge",
        "capacitor_charge",
        "capacitor_core",
        ("area", "length", "voltage"),
        "charge",
        "C",
        "Q = epsilon0*epsilon_r*A*U/d",
        "For a parallel-plate capacitor, Q = C U with C = epsilon0 epsilon_r A/d.",
    ),
    "parallel_plate_charge_radius": FormulaSpec(
        "parallel_plate_charge_radius",
        "capacitor_charge",
        "capacitor_core",
        ("length", "length", "voltage"),
        "charge",
        "C",
        "Q = epsilon0*epsilon_r*pi*r^2*U/d",
        "For circular parallel plates, Q = epsilon0 epsilon_r pi r^2 U/d.",
    ),
    "capacitor_voltage_charge": FormulaSpec(
        "capacitor_voltage_charge",
        "capacitor_final_voltage",
        "capacitor_core",
        ("charge", "capacitance"),
        "voltage",
        "V",
        "U = Q/C",
        "Capacitor voltage relation U = Q/C.",
    ),
    "capacitor_voltage_energy": FormulaSpec(
        "capacitor_voltage_energy",
        "capacitor_final_voltage",
        "capacitor_core",
        ("energy", "capacitance"),
        "voltage",
        "V",
        "U = sqrt(2W/C)",
        "Capacitor energy relation W = 1/2 C U² can be inverted for voltage.",
    ),
    "capacitor_voltage_isolated_dielectric": FormulaSpec(
        "capacitor_voltage_isolated_dielectric",
        "capacitor_final_voltage",
        "capacitor_core",
        ("voltage",),
        "voltage",
        "V",
        "U' = U/epsilon_r",
        "For an isolated capacitor, charge is constant, so inserting dielectric reduces voltage by epsilon_r.",
    ),
    "capacitor_voltage_isolated_distance_scaled": FormulaSpec(
        "capacitor_voltage_isolated_distance_scaled",
        "capacitor_final_voltage",
        "capacitor_core",
        ("voltage",),
        "voltage",
        "V",
        "U' = scale*U",
        "For an isolated parallel-plate capacitor, U = Q/C and C is inversely proportional to plate separation.",
    ),
    "capacitance_from_energy_voltage": FormulaSpec(
        "capacitance_from_energy_voltage",
        "capacitance",
        "capacitor_core",
        ("energy", "voltage"),
        "capacitance",
        "F",
        "C = 2W/U^2",
        "Capacitor energy relation W = 1/2 C U² can be inverted for capacitance.",
    ),
    "parallel_plate_capacitance": FormulaSpec(
        "parallel_plate_capacitance",
        "capacitance",
        "capacitor_core",
        ("area", "length"),
        "capacitance",
        "F",
        "C = epsilon0*epsilon_r*A/d",
        "Parallel-plate capacitance is C = epsilon0 epsilon_r A/d.",
    ),
    "parallel_plate_capacitance_radius": FormulaSpec(
        "parallel_plate_capacitance_radius",
        "capacitance",
        "capacitor_core",
        ("length", "length"),
        "capacitance",
        "F",
        "C = epsilon0*epsilon_r*pi*r^2/d",
        "For circular parallel plates, A = pi r^2 and C = epsilon0 epsilon_r A/d.",
    ),
    "capacitor_geometry_scaled_capacitance": FormulaSpec(
        "capacitor_geometry_scaled_capacitance",
        "capacitance",
        "capacitor_core",
        ("capacitance",),
        "capacitance",
        "F",
        "C' = C*(A'/A)*(d/d')*epsilon_r",
        "Parallel-plate capacitance is proportional to plate area and dielectric constant, and inversely proportional to separation.",
    ),
    "capacitor_series_unknown_from_final_charge": FormulaSpec(
        "capacitor_series_unknown_from_final_charge",
        "capacitance",
        "capacitor_core",
        ("capacitance", "voltage", "charge"),
        "capacitance",
        "F",
        "C_unknown = Q/(U_total - Q/C_known)",
        "For two capacitors in series, both carry the same charge and the source voltage is the sum of capacitor voltages.",
    ),
    "capacitor_energy_charge_voltage": FormulaSpec(
        "capacitor_energy_charge_voltage",
        "capacitor_energy",
        "capacitor_core",
        ("charge", "voltage"),
        "energy",
        "J",
        "W = 0.5*Q*U",
        "Capacitor energy can be computed from charge and voltage as W = 1/2 Q U.",
    ),
    "capacitor_energy_voltage_scaled": FormulaSpec(
        "capacitor_energy_voltage_scaled",
        "capacitor_energy",
        "capacitor_core",
        ("energy", "voltage", "voltage"),
        "energy",
        "J",
        "W2 = W1*(U2/U1)^2",
        "For fixed capacitance, capacitor energy is proportional to voltage squared.",
    ),
    "energy_loss_percent": FormulaSpec(
        "energy_loss_percent",
        "capacitor_energy",
        "capacitor_core",
        ("energy", "energy"),
        "percent",
        "%",
        "loss_percent = (W_initial-W_final)/W_initial*100",
        "Percentage energy loss is computed from the initial and final stored energies.",
    ),
    "conceptual_direct": FormulaSpec(
        "conceptual_direct",
        "conceptual",
        "conceptual_core",
        (),
        "dimensionless",
        "-",
        "deterministic conceptual rule",
        "Conceptual answers must be grounded in a known code-owned physics principle.",
    ),
    "yes_no_direct": FormulaSpec(
        "yes_no_direct",
        "conceptual",
        "conceptual_core",
        (),
        "dimensionless",
        "-",
        "deterministic yes/no condition",
        "Yes/No answers must be grounded in an explicit deterministic condition.",
    ),
    "measurement_error_direct": FormulaSpec(
        "measurement_error_direct",
        "measurement_error",
        "measurement_core",
        (),
        "multi_output",
        "mixed",
        "absolute/relative/mean measurement-error rule",
        "Measurement-error answers are computed from explicit measured, true, least-count, or stated uncertainty values.",
    ),
    "ohm_voltage": FormulaSpec(
        "ohm_voltage",
        "ohm_law",
        "dc_circuit_core",
        ("current", "resistance"),
        "voltage",
        "V",
        "U = I*R",
        "Ohm's law U = I R.",
    ),
    "ohm_current": FormulaSpec(
        "ohm_current",
        "ohm_law",
        "dc_circuit_core",
        ("voltage", "resistance"),
        "current",
        "A",
        "I = U/R",
        "Ohm's law I = U/R.",
    ),
    "ohm_resistance": FormulaSpec(
        "ohm_resistance",
        "ohm_law",
        "dc_circuit_core",
        ("voltage", "current"),
        "resistance",
        "Ω",
        "R = U/I",
        "Ohm's law R = U/I.",
    ),
    "ohm_current_power_resistance": FormulaSpec(
        "ohm_current_power_resistance",
        "ohm_law",
        "dc_circuit_core",
        ("power", "resistance"),
        "current",
        "A",
        "I = sqrt(P/R)",
        "For a resistor, P = I^2 R, so the current magnitude is I = sqrt(P/R).",
    ),
    "ohm_current_power_voltage": FormulaSpec(
        "ohm_current_power_voltage",
        "ohm_law",
        "dc_circuit_core",
        ("power", "voltage"),
        "current",
        "A",
        "I = P/U",
        "Electric power satisfies P = U I, so I = P/U.",
    ),
    "ohm_voltage_power_current": FormulaSpec(
        "ohm_voltage_power_current",
        "ohm_law",
        "dc_circuit_core",
        ("power", "current"),
        "voltage",
        "V",
        "U = P/I",
        "Electric power satisfies P = U I, so U = P/I.",
    ),
    "ohm_resistance_power_current": FormulaSpec(
        "ohm_resistance_power_current",
        "ohm_law",
        "dc_circuit_core",
        ("power", "current"),
        "resistance",
        "Ω",
        "R = P/I^2",
        "For a resistor, P = I^2 R, so R = P/I^2.",
    ),
    "ohm_resistance_voltage_power": FormulaSpec(
        "ohm_resistance_voltage_power",
        "ohm_law",
        "dc_circuit_core",
        ("voltage", "power"),
        "resistance",
        "Ω",
        "R = U^2/P",
        "For a resistor, P = U^2/R, so R = U^2/P.",
    ),
    "power_ui": FormulaSpec(
        "power_ui",
        "electric_power",
        "dc_circuit_core",
        ("voltage", "current"),
        "power",
        "W",
        "P = U*I",
        "Electric power relation P = U I.",
    ),
    "power_i2r": FormulaSpec(
        "power_i2r",
        "electric_power",
        "dc_circuit_core",
        ("current", "resistance"),
        "power",
        "W",
        "P = I^2 R",
        "Electric power relation P = I^2 R.",
    ),
    "power_u2r": FormulaSpec(
        "power_u2r",
        "electric_power",
        "dc_circuit_core",
        ("voltage", "resistance"),
        "power",
        "W",
        "P = U^2/R",
        "Electric power relation P = U^2/R.",
    ),
    "power_sum": FormulaSpec(
        "power_sum",
        "electric_power",
        "dc_circuit_core",
        ("power", "power"),
        "power",
        "W",
        "P_total = sum(P_i)",
        "For multiple loads in the same circuit statement, total power is the sum of the individual powers.",
    ),
    "energy_efficiency": FormulaSpec(
        "energy_efficiency",
        "electric_power",
        "dc_circuit_core",
        ("energy", "energy"),
        "percent",
        "%",
        "eta = useful/(useful+dissipated)*100",
        "Efficiency is useful output energy divided by total input energy.",
    ),
    "coulomb_force": FormulaSpec(
        "coulomb_force",
        "coulomb_force",
        "coulomb_core",
        ("charge", "charge", "length"),
        "force",
        "N",
        "F = k*abs(q1*q2)/r^2",
        "Coulomb force magnitude F = k |q1 q2| / r^2.",
    ),
    "coulomb_charge_from_force": FormulaSpec(
        "coulomb_charge_from_force",
        "coulomb_force",
        "coulomb_core",
        ("force", "charge", "length"),
        "charge",
        "C",
        "Q = F*r^2/(k*abs(q))",
        "Coulomb's law can be inverted to find an unknown point charge from force, known charge, and separation.",
    ),
    "electric_field_point": FormulaSpec(
        "electric_field_point",
        "electric_field_point",
        "coulomb_core",
        ("charge", "length"),
        "electric_field",
        "V/m",
        "E = k*abs(q)/r^2",
        "Point-charge field magnitude E = k |q| / r^2.",
    ),
    "electric_field_ring_axis": FormulaSpec(
        "electric_field_ring_axis",
        "electric_field_point",
        "field_core",
        ("charge", "length", "length"),
        "electric_field",
        "V/m",
        "E = k*abs(Q)*z/(R^2+z^2)^(3/2)",
        "For a uniformly charged thin ring, the axial electric field is E = kQz/(R^2+z^2)^(3/2).",
    ),
    "electric_field_semicircular_arc_center": FormulaSpec(
        "electric_field_semicircular_arc_center",
        "electric_field_point",
        "field_core",
        ("charge", "length"),
        "electric_field",
        "V/m",
        "E = 2*k*abs(Q)/(pi*R^2)",
        "For a uniformly charged semicircular arc, horizontal components cancel and the center field has magnitude 2kQ/(pi R^2).",
    ),
    "electric_field_parallel_sheets": FormulaSpec(
        "electric_field_parallel_sheets",
        "electric_field_point",
        "field_core",
        ("surface_charge_density",),
        "electric_field",
        "V/m",
        "E = sigma/epsilon0 or 0 by sheet superposition",
        "Wide charged sheets are solved by superposing each sheet field sigma/(2epsilon0).",
    ),
    "electric_field_infinite_line": FormulaSpec(
        "electric_field_infinite_line",
        "electric_field_point",
        "field_core",
        ("linear_charge_density", "length"),
        "electric_field",
        "V/m",
        "E = 2*k*abs(lambda)/r",
        "For an infinitely long uniformly charged wire, E = 2k|lambda|/r.",
    ),
    "electric_field_disk_axis": FormulaSpec(
        "electric_field_disk_axis",
        "electric_field_point",
        "field_core",
        ("surface_charge_density", "length", "length"),
        "electric_field",
        "V/m",
        "E_z = sigma/(2epsilon0)*(1 - z/sqrt(z^2+R^2))",
        "For a uniformly charged disk, the axial field is sigma/(2epsilon0)*(1-z/sqrt(z^2+R^2)).",
    ),
    "electric_field_finite_rod_perpendicular_end": FormulaSpec(
        "electric_field_finite_rod_perpendicular_end",
        "electric_field_point",
        "field_core",
        ("linear_charge_density", "length", "length"),
        "electric_field",
        "V/m",
        "E = vector integral over finite rod",
        "For a uniformly charged finite rod, deterministic integration sums perpendicular and axial components.",
    ),
    "electric_field_conducting_plate": FormulaSpec(
        "electric_field_conducting_plate",
        "electric_field_point",
        "field_core",
        ("charge", "area"),
        "electric_field",
        "V/m",
        "E = sigma/epsilon0",
        "Near a large uniformly charged conducting plate, E = sigma/epsilon0 outside the conductor.",
    ),
    "capacitor_series_field": FormulaSpec(
        "capacitor_series_field",
        "electric_field_point",
        "capacitor_core",
        ("capacitance", "capacitance", "voltage", "length"),
        "electric_field",
        "V/m",
        "E1 = U*C2/((C1+C2)*d1)",
        "Series capacitors carry the same charge, so the voltage across C1 is U*C2/(C1+C2) and E1 = U1/d1.",
    ),
    "electric_field_square_center_cancel_charge": FormulaSpec(
        "electric_field_square_center_cancel_charge",
        "electric_field_point",
        "symmetry_core",
        ("charge",),
        "charge",
        "C",
        "q_opposite = q_known",
        "At the square center, fields from equal charges on opposite vertices cancel pairwise.",
    ),
    "electric_field_point_dielectric": FormulaSpec(
        "electric_field_point_dielectric",
        "electric_field_point",
        "field_core",
        ("charge", "length"),
        "electric_field",
        "V/m",
        "E = k*abs(q)/(epsilon_r*r^2)",
        "In a uniform dielectric medium, the field of a point charge is reduced by the dielectric constant epsilon_r.",
    ),
    "point_charge_from_field_dielectric": FormulaSpec(
        "point_charge_from_field_dielectric",
        "electric_field_point",
        "field_core",
        ("electric_field", "length"),
        "charge",
        "C",
        "q = sign*E*epsilon_r*r^2/k",
        "For a point charge in a dielectric medium, E = k|q|/(epsilon_r r^2); field direction determines the sign.",
    ),
    "point_charge_field_midpoint_from_two_fields": FormulaSpec(
        "point_charge_field_midpoint_from_two_fields",
        "electric_field_point",
        "field_core",
        ("electric_field", "electric_field"),
        "electric_field",
        "V/m",
        "E_M = E_near / ((1+sqrt(E_near/E_far))/2)^2",
        "For a point charge on one field line, E is proportional to 1/r^2.",
    ),
    "dielectric_field_scaled": FormulaSpec(
        "dielectric_field_scaled",
        "electric_field_point",
        "field_core",
        ("electric_field",),
        "electric_field",
        "V/m",
        "E' = E/epsilon_r",
        "In a uniform dielectric medium, the field from the same point charge at the same distance is reduced by epsilon_r.",
    ),
    "electric_field_square_three_equal_vertex": FormulaSpec(
        "electric_field_square_three_equal_vertex",
        "electric_field_point",
        "field_core",
        ("charge", "length"),
        "electric_field",
        "V/m",
        "E_net = vector_sum at fourth square vertex",
        "For three equal charges at three vertices of a square, the field at the fourth vertex is found by vector superposition.",
    ),
    "electric_field_square_diagonal_alternating_zero": FormulaSpec(
        "electric_field_square_diagonal_alternating_zero",
        "electric_field_point",
        "symmetry_core",
        (),
        "electric_field",
        "V/m",
        "E_net = 0 by diagonal symmetry",
        "At the center of a square, equal charges on opposite vertices produce equal and opposite field vectors; both diagonal pairs cancel.",
    ),
    "electric_field_square_adjacent_alternating_center": FormulaSpec(
        "electric_field_square_adjacent_alternating_center",
        "electric_field_point",
        "symmetry_core",
        (),
        "electric_field",
        "V/m",
        "E_net = 4*sqrt(2)*k*q/a^2",
        "At the center of a square with adjacent same-sign pairs, vertical components cancel and horizontal components add.",
    ),
    "electric_field_centroid_equilateral_cancel_charge": FormulaSpec(
        "electric_field_centroid_equilateral_cancel_charge",
        "electric_field_point",
        "symmetry_core",
        ("charge",),
        "charge",
        "C",
        "q3 = q when q1 = q2 = q at the other equilateral vertices",
        "At the centroid of an equilateral triangle, equal charges at two vertices produce a resultant field canceled by an equal same-sign charge at the third vertex.",
    ),
    "electric_field_right_isosceles_identical_vertex": FormulaSpec(
        "electric_field_right_isosceles_identical_vertex",
        "electric_field_point",
        "field_core",
        ("charge", "length"),
        "electric_field",
        "V/m",
        "E_net = sqrt(2)*k*abs(q)/a^2",
        "At the right-angle vertex of an isosceles right triangle, equal charges on the other two vertices produce perpendicular equal fields.",
    ),
    "electric_field_force": FormulaSpec(
        "electric_field_force",
        "electric_field_force",
        "field_core",
        ("force", "charge"),
        "electric_field",
        "V/m",
        "E = F/abs(q)",
        "Electric field magnitude relation E = F/|q|.",
    ),
    "electric_field_equilibrium_mg": FormulaSpec(
        "electric_field_equilibrium_mg",
        "electric_field_point",
        "field_core",
        ("mass", "charge", "acceleration"),
        "electric_field",
        "V/m",
        "E = m*g/abs(q)",
        "For vertical equilibrium of a charged particle, electric force balances weight: |q|E = mg.",
    ),
    "force_in_electric_field": FormulaSpec(
        "force_in_electric_field",
        "force_in_electric_field",
        "field_core",
        ("charge", "electric_field"),
        "force",
        "N",
        "F = abs(q)*E",
        "Electric force magnitude relation F = |q|E.",
    ),
    "electric_equilibrium_charge": FormulaSpec(
        "electric_equilibrium_charge",
        "force_in_electric_field",
        "field_core",
        ("mass", "electric_field", "acceleration"),
        "charge",
        "C",
        "q = m*g/E",
        "For vertical equilibrium of a charged particle, electric force balances weight: |q|E = mg.",
    ),
    "electric_equilibrium_mass_angle": FormulaSpec(
        "electric_equilibrium_mass_angle",
        "force_in_electric_field",
        "field_core",
        ("charge", "electric_field", "angle"),
        "mass",
        "kg",
        "m = abs(q)*E/(g*tan(theta))",
        "For a suspended charged particle in horizontal electric-field equilibrium with angle theta from vertical, tan(theta)=|q|E/(mg).",
    ),
    "electric_equilibrium_deflection_angle": FormulaSpec(
        "electric_equilibrium_deflection_angle",
        "force_in_electric_field",
        "field_core",
        ("mass", "charge", "electric_field", "acceleration"),
        "angle",
        "deg",
        "theta = atan(abs(q)*E/(m*g))",
        "For a suspended charged particle in horizontal electric-field equilibrium, tan(theta)=|q|E/(mg).",
    ),
    "uniform_field_voltage": FormulaSpec(
        "uniform_field_voltage",
        "uniform_field_voltage",
        "field_core",
        ("electric_field", "length"),
        "voltage",
        "V",
        "U = E*d",
        "Uniform electric field relation U = E d.",
    ),
    "electric_potential_point": FormulaSpec(
        "electric_potential_point",
        "electric_potential_point",
        "coulomb_core",
        ("charge", "length"),
        "voltage",
        "V",
        "V = k*q/r",
        "Point-charge potential V = kq/r.",
    ),
    "electrostatic_energy": FormulaSpec(
        "electrostatic_energy",
        "electrostatic_energy",
        "coulomb_core",
        ("charge", "charge", "length"),
        "energy",
        "J",
        "U = k*q1*q2/r",
        "Electrostatic potential energy U = k q1 q2 / r.",
    ),
    "lc_frequency": FormulaSpec(
        "lc_frequency",
        "lc_frequency",
        "lc_core",
        ("inductance", "capacitance"),
        "frequency",
        "Hz",
        "f = 1/(2*pi*sqrt(L*C))",
        "LC resonance frequency f = 1/(2π√(LC)).",
    ),
    "frequency_from_period": FormulaSpec(
        "frequency_from_period",
        "lc_frequency",
        "lc_core",
        ("time",),
        "frequency",
        "Hz",
        "f = 1/T",
        "Oscillation frequency and period satisfy f = 1/T.",
    ),
    "lc_period": FormulaSpec(
        "lc_period",
        "lc_period",
        "lc_core",
        ("inductance", "capacitance"),
        "time",
        "s",
        "T = 2*pi*sqrt(L*C)",
        "LC period T = 2π√(LC).",
    ),
    "lc_energy_complement": FormulaSpec(
        "lc_energy_complement",
        "lc_energy",
        "lc_core",
        ("energy", "energy"),
        "energy",
        "J",
        "W_other = W_total - W_known",
        "In an ideal LC circuit, total energy is conserved and splits between electric and magnetic energy.",
    ),
    "inductor_energy": FormulaSpec(
        "inductor_energy",
        "inductor_energy",
        "magnetic_core",
        ("inductance", "current"),
        "energy",
        "J",
        "W = 0.5*L*I^2",
        "Inductor energy relation W = 1/2 L I^2.",
    ),
    "inductor_current_from_energy": FormulaSpec(
        "inductor_current_from_energy",
        "inductor_energy",
        "magnetic_core",
        ("energy", "inductance"),
        "current",
        "A",
        "I = sqrt(2W/L)",
        "Inductor energy relation W = 1/2 L I^2 can be inverted for current.",
    ),
    "inductive_reactance": FormulaSpec(
        "inductive_reactance",
        "inductive_reactance",
        "rlc_core",
        ("frequency", "inductance"),
        "resistance",
        "Ω",
        "XL = 2*pi*f*L",
        "Inductive reactance XL = 2πfL.",
    ),
    "capacitive_reactance": FormulaSpec(
        "capacitive_reactance",
        "capacitive_reactance",
        "rlc_core",
        ("frequency", "capacitance"),
        "resistance",
        "Ω",
        "XC = 1/(2*pi*f*C)",
        "Capacitive reactance XC = 1/(2πfC).",
    ),
    "rlc_impedance": FormulaSpec(
        "rlc_impedance",
        "rlc_impedance",
        "rlc_core",
        ("resistance", "resistance", "resistance"),
        "resistance",
        "Ω",
        "Z = sqrt(R^2 + (XL-XC)^2)",
        "Series RLC impedance Z = sqrt(R^2 + (XL - XC)^2).",
    ),
    "rlc_impedance_from_rlcf": FormulaSpec(
        "rlc_impedance_from_rlcf",
        "rlc_impedance",
        "rlc_core",
        ("resistance", "inductance", "capacitance", "frequency"),
        "resistance",
        "Ω",
        "Z = sqrt(R^2 + (2*pi*f*L - 1/(2*pi*f*C))^2)",
        "For a series RLC circuit, compute XL and XC from f, L, C before computing impedance.",
    ),
    "rlc_impedance_voltage_current": FormulaSpec(
        "rlc_impedance_voltage_current",
        "rlc_impedance",
        "rlc_core",
        ("voltage", "current"),
        "resistance",
        "Ω",
        "Z = U/I",
        "Circuit impedance magnitude follows Z = U/I for voltage and current magnitudes.",
    ),
    "rlc_resonance_resistance_from_impedance": FormulaSpec(
        "rlc_resonance_resistance_from_impedance",
        "ohm_law",
        "rlc_core",
        ("resistance",),
        "resistance",
        "Ω",
        "R = Z at resonance",
        "At series RLC resonance, XL = XC, so impedance equals pure resistance R.",
    ),
    "lc_resonance_capacitance": FormulaSpec(
        "lc_resonance_capacitance",
        "capacitance",
        "lc_core",
        ("inductance", "frequency"),
        "capacitance",
        "F",
        "C = 1/((2*pi*f)^2*L)",
        "LC/RLC resonance frequency satisfies f = 1/(2*pi*sqrt(L*C)).",
    ),
    "lc_resonance_inductance": FormulaSpec(
        "lc_resonance_inductance",
        "inductance",
        "lc_core",
        ("capacitance", "frequency"),
        "inductance",
        "H",
        "L = 1/((2*pi*f)^2*C)",
        "LC/RLC resonance frequency satisfies f = 1/(2*pi*sqrt(L*C)).",
    ),
    "inductance_from_energy_current": FormulaSpec(
        "inductance_from_energy_current",
        "inductance",
        "magnetic_core",
        ("energy", "current"),
        "inductance",
        "H",
        "L = 2W/I^2",
        "Inductor energy relation W = 1/2 L I^2 can be inverted for inductance.",
    ),
    "power_factor": FormulaSpec(
        "power_factor",
        "power_factor",
        "rlc_core",
        ("resistance", "resistance"),
        "dimensionless",
        "-",
        "cos_phi = R/Z",
        "Power factor cos(phi) = R/Z.",
    ),
    "solenoid_magnetic_field": FormulaSpec(
        "solenoid_magnetic_field",
        "solenoid_magnetic_field",
        "magnetic_core",
        ("turn_density", "current"),
        "magnetic_field",
        "T",
        "B = mu0*n*I",
        "Long-solenoid magnetic field B = μ0 n I.",
    ),
    "solenoid_magnetic_field_turns_length": FormulaSpec(
        "solenoid_magnetic_field_turns_length",
        "solenoid_magnetic_field",
        "magnetic_core",
        ("count", "length", "current"),
        "magnetic_field",
        "T",
        "B = mu0*(N/l)*I",
        "For a long solenoid with N turns over length l, turn density n = N/l and B = μ0 n I.",
    ),
    "solenoid_turn_density": FormulaSpec(
        "solenoid_turn_density",
        "turn_density",
        "magnetic_core",
        ("count", "length"),
        "turn_density",
        "turns/m",
        "n = N/l",
        "Solenoid turn density is number of turns per unit length.",
    ),
    "solenoid_inductance": FormulaSpec(
        "solenoid_inductance",
        "solenoid_inductance",
        "magnetic_core",
        ("count", "area", "length"),
        "inductance",
        "H",
        "L = mu0*N^2*A/l",
        "Long-solenoid inductance is L = mu0 N^2 A/l for an air-core solenoid.",
    ),
    "magnetic_flux": FormulaSpec(
        "magnetic_flux",
        "magnetic_flux",
        "magnetic_core",
        ("magnetic_field", "area"),
        "magnetic_flux",
        "Wb",
        "Phi = B*S",
        "Magnetic flux through a perpendicular area Φ = B S.",
    ),
    "solenoid_flux_one_turn": FormulaSpec(
        "solenoid_flux_one_turn",
        "magnetic_flux",
        "magnetic_core",
        ("area", "turn_density", "current"),
        "magnetic_flux",
        "Wb",
        "Phi = mu0*n*I*A",
        "Flux through one turn of a long solenoid is Phi = B A with B = mu0 n I.",
    ),
    "resultant_two_forces": FormulaSpec(
        "resultant_two_forces",
        "resultant_force",
        "vector_core",
        ("force", "force"),
        "force",
        "N",
        "R = sqrt(F1^2 + F2^2 + 2*F1*F2*cos(theta))",
        "Resultant of two forces by the law of cosines.",
    ),
    "resultant_two_forces_angle": FormulaSpec(
        "resultant_two_forces_angle",
        "resultant_force",
        "vector_core",
        ("force", "force"),
        "angle",
        "deg",
        "theta = arccos((R^2-F1^2-F2^2)/(2*F1*F2))",
        "The angle between two forces follows from the law of cosines.",
    ),
    "coulomb_equal_charge": FormulaSpec(
        "coulomb_equal_charge",
        "equal_charge_coulomb",
        "coulomb_core",
        ("force", "length"),
        "charge",
        "C",
        "q = sqrt(F*r^2/k)",
        "For equal point charges, Coulomb's law gives q = sqrt(F r^2/k).",
    ),
    "coulomb_perpendicular_bisector_opposite_charges": FormulaSpec(
        "coulomb_perpendicular_bisector_opposite_charges",
        "coulomb_force",
        "coulomb_core",
        ("charge", "charge", "charge", "length", "length"),
        "force",
        "N",
        "F = 2*k*|Q*q0|*a/(a^2+h^2)^(3/2)",
        "For equal opposite charges, a test charge on the perpendicular bisector has vertical components cancel and horizontal components add.",
    ),
    "multi_output_direct": FormulaSpec(
        "multi_output_direct",
        "multi_output",
        "conceptual_core",
        (),
        "dimensionless",
        "-",
        "deterministic sub-solvers",
        "Solve each requested output with deterministic sub-solvers in target order.",
    ),
    "symmetric_zero_force": FormulaSpec(
        "symmetric_zero_force",
        "coulomb_force",
        "symmetry_core",
        (),
        "force",
        "N",
        "F_net = 0 by symmetry",
        "Identical symmetric source charges produce zero net force at the symmetry center.",
    ),
    "coulomb_right_isosceles_identical_vertex": FormulaSpec(
        "coulomb_right_isosceles_identical_vertex",
        "coulomb_force",
        "coulomb_core",
        ("charge", "length"),
        "force",
        "N",
        "F_net = sqrt(2)*k*q^2/a^2",
        "For three identical charges on a right-isosceles triangle, forces on the right-angle charge are equal and perpendicular.",
    ),
    "coulomb_force_triangle_sides": FormulaSpec(
        "coulomb_force_triangle_sides",
        "coulomb_force",
        "coulomb_core",
        ("charge", "charge", "charge", "length", "length", "length"),
        "force",
        "N",
        "F_net = |sum(k*q_i*q_target*r_i/r_i^3)|",
        "For a test charge and two source charges with all three side lengths known, reconstruct the triangle and sum force vectors.",
    ),
    "electric_field_two_charge_isosceles": FormulaSpec(
        "electric_field_two_charge_isosceles",
        "electric_field_point",
        "field_core",
        ("charge", "charge", "length", "length"),
        "electric_field",
        "V/m",
        "E = 2*k*|q|*component/r^3",
        "For equal-magnitude two-charge isosceles geometry, resolve field vectors into symmetry-axis components.",
    ),
    "electric_field_two_charge_triangle_sides": FormulaSpec(
        "electric_field_two_charge_triangle_sides",
        "electric_field_point",
        "field_core",
        ("charge", "charge", "length", "length", "length"),
        "electric_field",
        "V/m",
        "E_net = |sum(k*q_i*r_i/r_i^3)|",
        "For two source charges and a field point with all three side lengths known, reconstruct the triangle and sum field vectors.",
    ),
    "electric_field_two_charge_angle": FormulaSpec(
        "electric_field_two_charge_angle",
        "electric_field_point",
        "field_core",
        ("charge", "charge", "length", "angle"),
        "electric_field",
        "V/m",
        "E_net = sqrt(E1^2 + E2^2 + 2*E1*E2*cos(phi))",
        "For two point-charge fields with known distance(s) and included angle, combine the two field vectors by the law of cosines.",
    ),
    "electric_field_equilateral_vertex": FormulaSpec(
        "electric_field_equilateral_vertex",
        "electric_field_point",
        "field_core",
        ("charge", "charge", "length"),
        "electric_field",
        "V/m",
        "E = sqrt(3)*k*|q|/a^2 or k*|q|/a^2",
        "At a vertex of an equilateral triangle, two equal field vectors combine by symmetry.",
    ),
    "electric_field_zero_line_two_charges": FormulaSpec(
        "electric_field_zero_line_two_charges",
        "electric_field_point",
        "field_core",
        ("charge", "charge", "length"),
        "length",
        "m",
        "E_net = 0 on the line joining two point charges",
        "For two point charges on a line, the zero-field point is solved from |q1|/r1^2 = |q2|/r2^2 with the valid same-sign or opposite-sign region.",
    ),
    "parallel_plate_dielectric_constant": FormulaSpec(
        "parallel_plate_dielectric_constant",
        "dielectric_constant",
        "capacitor_core",
        ("capacitance", "area", "length"),
        "dimensionless",
        "-",
        "epsilon_r = C*d/(epsilon0*A)",
        "Parallel-plate capacitance gives epsilon_r = C d / (epsilon0 A).",
    ),
    "capacitor_charge_sharing_voltage": FormulaSpec(
        "capacitor_charge_sharing_voltage",
        "capacitor_final_voltage",
        "capacitor_core",
        ("capacitance", "capacitance", "voltage", "voltage"),
        "voltage",
        "V",
        "U_final = (C1*U1 + C2*U2)/(C1+C2)",
        "When like-charged capacitor plates are connected, total charge is conserved.",
    ),
    "capacitor_series_voltage": FormulaSpec(
        "capacitor_series_voltage",
        "capacitor_final_voltage",
        "capacitor_core",
        ("capacitance", "capacitance", "voltage"),
        "voltage",
        "V",
        "U_Ci = Q/Ci, Q = C_eq*U_total",
        "Capacitors in series carry the same charge, so voltage divides inversely with capacitance.",
    ),
    "parallel_plate_breakdown_charge": FormulaSpec(
        "parallel_plate_breakdown_charge",
        "capacitor_charge",
        "capacitor_core",
        ("length", "electric_field"),
        "charge",
        "C",
        "Q_max = epsilon0*pi*r^2*E_max",
        "For air-filled circular parallel plates at breakdown, Qmax = epsilon0 A Emax.",
    ),
    "capacitor_connected_voltage_constant": FormulaSpec(
        "capacitor_connected_voltage_constant",
        "capacitor_final_voltage",
        "capacitor_core",
        ("voltage",),
        "voltage",
        "V",
        "U_final = U_source",
        "A capacitor that remains connected to an ideal source keeps the source voltage.",
    ),
    "capacitor_energy_shared_identical": FormulaSpec(
        "capacitor_energy_shared_identical",
        "capacitor_energy",
        "capacitor_core",
        ("capacitance", "voltage"),
        "energy",
        "J",
        "W_final = W_initial/n",
        "If an isolated capacitor shares charge among n identical capacitors, total energy becomes W_initial/n.",
    ),
    "capacitor_energy_voltage_percent": FormulaSpec(
        "capacitor_energy_voltage_percent",
        "capacitor_energy",
        "capacitor_core",
        ("voltage", "voltage"),
        "percent",
        "%",
        "percent = (U_final/U_initial)^2*100",
        "For unchanged capacitance, stored capacitor energy is proportional to U^2.",
    ),
    "rlc_current_impedance": FormulaSpec(
        "rlc_current_impedance",
        "ohm_law",
        "rlc_core",
        ("voltage", "resistance"),
        "current",
        "A",
        "I = U/Z",
        "For an AC circuit with known impedance, RMS current is I = U/Z.",
    ),
    "rlc_voltage_resonance": FormulaSpec(
        "rlc_voltage_resonance",
        "ohm_law",
        "rlc_core",
        ("current", "resistance"),
        "voltage",
        "V",
        "U = I*R at resonance",
        "At series RLC resonance, impedance equals resistance.",
    ),
    "rlc_current_resonance": FormulaSpec(
        "rlc_current_resonance",
        "ohm_law",
        "rlc_core",
        ("voltage", "resistance"),
        "current",
        "A",
        "I = U/R at resonance",
        "At series RLC resonance, impedance equals resistance.",
    ),
    "rlc_power_resonance": FormulaSpec(
        "rlc_power_resonance",
        "electric_power",
        "rlc_core",
        ("voltage", "resistance"),
        "power",
        "W",
        "P = U^2/R at resonance",
        "At series RLC resonance, all supplied power is dissipated in R.",
    ),
    "rlc_power_impedance": FormulaSpec(
        "rlc_power_impedance",
        "electric_power",
        "rlc_core",
        ("voltage", "resistance", "resistance"),
        "power",
        "W",
        "P = U^2*R/Z^2",
        "For a series RLC circuit, real power is P = U^2 R / Z^2.",
    ),
    "rlc_quadrature_current": FormulaSpec(
        "rlc_quadrature_current",
        "ohm_law",
        "rlc_core",
        ("voltage", "resistance", "resistance"),
        "current",
        "A",
        "I = U/(R1+R2)",
        "For the LCω²=1 two-segment quadrature pattern, the equivalent impedance is resistive R1+R2.",
    ),
    "rlc_quadrature_power": FormulaSpec(
        "rlc_quadrature_power",
        "electric_power",
        "rlc_core",
        ("voltage", "resistance", "resistance"),
        "power",
        "W",
        "P = U^2/(R1+R2)",
        "For the LCω²=1 two-segment quadrature pattern, total power is U²/(R1+R2).",
    ),
    "rlc_quadrature_power_factor": FormulaSpec(
        "rlc_quadrature_power_factor",
        "power_factor",
        "rlc_core",
        ("resistance", "resistance"),
        "dimensionless",
        "-",
        "cos_phi = 1",
        "For the LCω²=1 two-segment quadrature pattern, the total circuit is purely resistive.",
    ),
    "rlc_quadrature_segment_voltage": FormulaSpec(
        "rlc_quadrature_segment_voltage",
        "ohm_law",
        "rlc_core",
        ("voltage", "resistance", "resistance"),
        "voltage",
        "V",
        "U_segment = U*sqrt(R_segment/(R1+R2))",
        "For the LCω²=1 quadrature pattern, segment RMS voltage is U sqrt(R_segment/(R1+R2)).",
    ),
    "rlc_quadrature_segment_power_same_voltage": FormulaSpec(
        "rlc_quadrature_segment_power_same_voltage",
        "electric_power",
        "rlc_core",
        ("voltage", "resistance", "resistance"),
        "power",
        "W",
        "P_MB = U^2/(R1+R2)",
        "For the LCω²=1 quadrature pattern, applying the same RMS voltage across MB gives P_MB = U²/(R1+R2).",
    ),
    "rlc_frequency_resonance_resistor_voltage": FormulaSpec(
        "rlc_frequency_resonance_resistor_voltage",
        "ohm_law",
        "rlc_core",
        ("voltage", "resistance", "resistance"),
        "voltage",
        "V",
        "U_R = U when X_L' = X_C'",
        "If changing frequency makes X_L equal X_C, the series RLC circuit is at resonance and U_R = U.",
    ),
    "rlc_frequency_resonance_power": FormulaSpec(
        "rlc_frequency_resonance_power",
        "electric_power",
        "rlc_core",
        ("voltage", "resistance", "resistance", "resistance"),
        "power",
        "W",
        "P = U^2/R when X_L' = X_C'",
        "If changing frequency makes X_L equal X_C, the resistor dissipates P = U²/R.",
    ),
    "rlc_frequency_resonance_current": FormulaSpec(
        "rlc_frequency_resonance_current",
        "ohm_law",
        "rlc_core",
        ("voltage", "resistance", "resistance", "resistance"),
        "current",
        "A",
        "I = U/R when X_L' = X_C'",
        "If changing frequency makes X_L equal X_C, the series RLC circuit is at resonance and current is U/R.",
    ),
    "rlc_quadrature_missing_resistance": FormulaSpec(
        "rlc_quadrature_missing_resistance",
        "ohm_law",
        "rlc_core",
        ("voltage", "power", "resistance"),
        "resistance",
        "Ω",
        "R_missing = U^2/P - R_known",
        "For the LCω²=1 quadrature pattern, total real resistance is U²/P = R1 + R2.",
    ),
    "rlc_initial_reactance_from_doubled_frequency_current": FormulaSpec(
        "rlc_initial_reactance_from_doubled_frequency_current",
        "ohm_law",
        "rlc_core",
        ("resistance", "current", "current"),
        "resistance",
        "Ω",
        "X_L0 = sqrt((I0*R/I2)^2 - R^2)/(2 - 1/2)",
        "At resonance X_L0 = X_C0; when frequency doubles, net reactance is 2X_L0 - X_C0/2.",
    ),
    "rlc_resonance_inductor_voltage": FormulaSpec(
        "rlc_resonance_inductor_voltage",
        "ohm_law",
        "rlc_core",
        ("voltage", "resistance", "inductance", "capacitance"),
        "voltage",
        "V",
        "U_L = (U/R)*(L/sqrt(LC))",
        "At series RLC resonance, current is U/R and inductor voltage is I X_L with X_L = omega0 L.",
    ),
    "terminal_voltage_internal_resistance": FormulaSpec(
        "terminal_voltage_internal_resistance",
        "internal_resistance",
        "internal_resistance_core",
        ("voltage", "current", "resistance"),
        "voltage",
        "V",
        "U_terminal = E - I*r",
        "A source with internal resistance has terminal voltage U = E - Ir.",
    ),
    "source_current_internal_resistance": FormulaSpec(
        "source_current_internal_resistance",
        "internal_resistance",
        "internal_resistance_core",
        ("voltage", "resistance", "resistance"),
        "current",
        "A",
        "I = E/(R+r)",
        "For a source with internal resistance and load resistance, I = E/(R+r).",
    ),
    "joule_heating_i2rt": FormulaSpec(
        "joule_heating_i2rt",
        "joule_heating",
        "joule_heating_core",
        ("current", "resistance", "time"),
        "energy",
        "J",
        "Q_heat = I^2*R*t",
        "Joule heating in a resistor is Q = I^2 R t.",
    ),
    "electric_work_voltage": FormulaSpec(
        "electric_work_voltage",
        "electric_work",
        "field_core",
        ("charge", "voltage"),
        "energy",
        "J",
        "A = q*U",
        "Electric work through a potential difference is A = qU.",
    ),
    "uniform_field_strength": FormulaSpec(
        "uniform_field_strength",
        "uniform_field",
        "field_core",
        ("voltage", "length"),
        "electric_field",
        "V/m",
        "E = U/d",
        "A uniform electric field between plates has E = U/d.",
    ),
    "charged_particle_speed_voltage": FormulaSpec(
        "charged_particle_speed_voltage",
        "charged_particle_motion",
        "charged_particle_core",
        ("charge", "voltage", "mass"),
        "velocity",
        "m/s",
        "v = sqrt(2*abs(q)*U/m)",
        "A charged particle accelerated through voltage U gains kinetic energy |q|U.",
    ),
    "charged_particle_stopping_distance_uniform_field": FormulaSpec(
        "charged_particle_stopping_distance_uniform_field",
        "charged_particle_motion",
        "charged_particle_core",
        ("electric_field", "velocity"),
        "length",
        "m",
        "s = m*v0^2/(2*abs(q)*E)",
        "A charged particle moving against the electric force stops after converting kinetic energy through field work.",
    ),
    "rc_time_constant": FormulaSpec(
        "rc_time_constant",
        "rc_circuit",
        "rc_core",
        ("resistance", "capacitance"),
        "time",
        "s",
        "tau = R*C",
        "The RC time constant is tau = RC.",
    ),
    "rc_charge_fraction_time": FormulaSpec(
        "rc_charge_fraction_time",
        "rc_circuit",
        "rc_core",
        ("resistance", "capacitance", "percent"),
        "time",
        "s",
        "1 - exp(-t/(RC)) = fraction",
        "For RC charging, capacitor voltage or charge reaches a fraction f after solving 1 - exp(-t/RC) = f.",
    ),
    "rc_discharge_fraction_time": FormulaSpec(
        "rc_discharge_fraction_time",
        "rc_circuit",
        "rc_core",
        ("resistance", "capacitance", "percent"),
        "time",
        "s",
        "exp(-t/(RC)) = fraction",
        "For RC discharging, capacitor voltage or charge remains at a fraction f after solving exp(-t/RC) = f.",
    ),
    "ideal_transformer_voltage_ratio": FormulaSpec(
        "ideal_transformer_voltage_ratio",
        "transformer",
        "transformer_core",
        ("voltage", "count", "count"),
        "voltage",
        "V",
        "U2 = U1*N2/N1",
        "For an ideal transformer, U1/U2 = N1/N2.",
    ),
    "drift_current": FormulaSpec(
        "drift_current",
        "drift_current",
        "dc_circuit_core",
        ("number_density", "charge", "area", "velocity"),
        "current",
        "A",
        "I = n*abs(q)*A*v_d",
        "Microscopic current in a conductor is I = n |q| A v_d.",
    ),
    "wheatstone_balance_resistance": FormulaSpec(
        "wheatstone_balance_resistance",
        "wheatstone_bridge",
        "topology_core",
        ("resistance", "resistance", "resistance"),
        "resistance",
        "Ω",
        "R4 = R2*R3/R1",
        "For a balanced Wheatstone bridge, R1/R2 = R3/R4.",
    ),
    "lorentz_force_magnetic": FormulaSpec(
        "lorentz_force_magnetic",
        "lorentz_force",
        "magnetic_core",
        ("charge", "velocity", "magnetic_field"),
        "force",
        "N",
        "F = abs(q)*v*B*sin(theta)",
        "Magnetic Lorentz force magnitude is F = |q|vBsin(theta).",
    ),
    "wire_magnetic_force": FormulaSpec(
        "wire_magnetic_force",
        "wire_magnetic_force",
        "magnetic_core",
        ("magnetic_field", "current", "length"),
        "force",
        "N",
        "F = B*I*l*sin(theta)",
        "A current-carrying wire in a magnetic field experiences F = BIlsin(theta).",
    ),
    "faraday_flux_emf": FormulaSpec(
        "faraday_flux_emf",
        "faraday_induction",
        "induction_core",
        ("count", "magnetic_flux", "time"),
        "voltage",
        "V",
        "abs(emf) = N*abs(delta_phi)/delta_t",
        "Faraday induction gives induced emf from flux-linkage change.",
    ),
    "self_induced_emf": FormulaSpec(
        "self_induced_emf",
        "faraday_induction",
        "induction_core",
        ("inductance", "current", "time"),
        "voltage",
        "V",
        "abs(emf) = L*abs(delta_i)/delta_t",
        "Self-induced emf magnitude follows |e| = L |delta I| / delta t.",
    ),
}

FORMULA_IDS: FrozenSet[str] = frozenset(FORMULA_REGISTRY)
